### PR TITLE
Update localuser.js home button

### PR DESCRIPTION
**Pull request by kalebplayz125**
hai powmpy now we can have home button image support ^w^
_mwa_

### CODE REVIEW

**Comment by phoebe-leong** [comment]
Thanks <3
I'll test it out when I can

**Comment by phoebe-leong** [comment]
Hey this is cool and the home button looks good. I'm just wondering though, why did you remove the "Darker" theme selection in ``localuser.js``?

**Comment by kalebplayz125** [comment]
I didnt delete it I downloaded the localuser.js file from math's client (before ts merge)

**Comment by phoebe-leong** [comment]
oh
well can u add it plz

**Comment by phoebe-leong** [comment]
okay i fixed it
ill test it tmrw

**Pull request closed without merging**
